import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const dataPath = path.join(root, "data", "works.json");
const works = JSON.parse(fs.readFileSync(dataPath, "utf8")).filter((w) => w?.id && w?.image).map((w) => ({ ...w, category: w.category === "women" ? "portrait" : w.category === "web_ui" ? "web-ui" : w.category }));
const labels = { general: "综合作品", portrait: "人像", "web-ui": "视觉系 UI" };
const base = "https://aurora-ai-lab.github.io/MINA/";
const esc = (s = "") => String(s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
const stripQuery = (s) => String(s).split("?")[0];
const titleOf = (w) => `${w.title} · Coolcat`;
const rel = (p) => p.replaceAll(path.sep, "/");
const write = (file, html) => { const target = path.join(root, file); fs.mkdirSync(path.dirname(target), { recursive: true }); fs.writeFileSync(target, html); };
const card = (w, level = 1) => { const up = "../".repeat(level); const image = `${up}${w.thumb || w.image}`; return `<a class="static-card" href="${up}work/${encodeURIComponent(w.id)}/"><figure><img src="${image}" alt="${esc(w.title)}" loading="lazy"><figcaption><strong>${esc(w.title)}</strong><small>${esc(w.date)} · ${(w.tags || []).slice(0, 2).map((t) => `#${esc(t)}`).join(" ")}</small></figcaption></figure></a>`; };
const shell = ({ title, description, level = 0, route = "", content, og = "images/og/coolcat-og.webp" }) => { const up = "../".repeat(level); return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#07050d"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:image" content="${base}${og}"><link rel="canonical" href="${base}${route}"><link rel="icon" href="${up}assets/favicon.svg" type="image/svg+xml"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500;600;700&family=JetBrains+Mono:wght@400;500;600&display=swap" rel="stylesheet"><link rel="stylesheet" href="${up}assets/style.css"></head><body class="sky-subpage"><header class="site-header"><div class="header-inner"><a class="brand" href="${up}" aria-label="Coolcat 首页"><span class="wordmark">Coolcat</span><span class="brand-note">AI ART / PROMPTS</span></a><nav class="site-nav" aria-label="主要导航"><a href="${up}gallery/">作品</a><a href="${up}gallery/portrait/">人像</a><a href="${up}gallery/ui/">UI</a><a href="${up}about/">关于</a></nav><a class="x-link" href="https://x.com/minaoneday" target="_blank" rel="noopener">@minaoneday ↗</a></div></header><main>${content}</main><footer class="site-footer"><div><strong>Coolcat</strong><span>AI art archive by <a href="https://x.com/minaoneday" target="_blank" rel="noopener">@minaoneday</a></span></div><nav><a href="${up}gallery/">作品</a><a href="${up}about/">说明</a><a href="https://x.com/minaoneday" target="_blank" rel="noopener">X ↗</a></nav><p>© 2026 Coolcat · 每一张都附完整提示词</p></footer></body></html>`; };
const galleryPage = (title, description, items, level) => `<section class="static-page"><p class="eyebrow">COOLCAT / GALLERY</p><h1>${esc(title)}</h1><p class="static-lede">${esc(description)}</p><div class="static-grid">${items.map((w) => card(w, level)).join("")}</div></section>`;

write("gallery/index.html", shell({ title: "全部 AI 作品与提示词 · Coolcat", description: `全部 ${works.length} 件 AI 作品与完整提示词。`, level: 1, route: "gallery/", content: galleryPage("全部作品", `共 ${works.length} 件作品，按分类、标签和关键词浏览。`, works, 1) }));
for (const [cat, label] of Object.entries(labels)) { const items = works.filter((w) => w.category === cat); const folder = cat === "web-ui" ? "ui" : cat; write(`gallery/${folder}/index.html`, shell({ title: `AI ${label}提示词 · ${items.length} 件作品 · Coolcat`, description: `${items.length} 件${label}作品，每一张都附完整提示词。`, level: 2, route: `gallery/${folder}/`, content: galleryPage(label, `${items.length} 件作品 · 每一张都附完整提示词。`, items, 2) })); }

const tagCounts = new Map(); for (const w of works) for (const tag of w.tags || []) tagCounts.set(tag, (tagCounts.get(tag) || 0) + 1);
for (const [tag, count] of tagCounts) if (count >= 3) { const items = works.filter((w) => (w.tags || []).includes(tag)); const slug = tag.replace(/[\\/:*?"<>|]/g, "-").trim() || encodeURIComponent(tag); write(`tag/${slug}/index.html`, shell({ title: `${tag} AI 绘画提示词 · Coolcat`, description: `${count} 件包含“${tag}”标签的 AI 作品与完整提示词。`, level: 2, route: `tag/${slug}/`, content: galleryPage(`#${tag}`, `${count} 件相关作品`, items, 2) })); }

const byDate = [...works].sort((a, b) => String(b.date).localeCompare(String(a.date)) || String(b.id).localeCompare(String(a.id)));
for (let i = 0; i < byDate.length; i++) { const w = byDate[i], related = works.filter((x) => x.id !== w.id && (x.tags || []).some((t) => (w.tags || []).includes(t))).slice(0, 6); const image = `../../${w.image}`; const prompt = String(w.prompt || ""); const desc = prompt.replace(/\s+/g, " ").slice(0, 150); const tags = (w.tags || []).map((t) => { const slug = t.replace(/[\\/:*?"<>|]/g, "-").trim(); return tagCounts.get(t) >= 3 ? `<a class="chip" href="../../tag/${slug}/">#${esc(t)}</a>` : `<span class="chip">#${esc(t)}</span>`; }).join(""); const prev = byDate[(i - 1 + byDate.length) % byDate.length], next = byDate[(i + 1) % byDate.length]; const content = `<article class="detail-page"><div class="detail-media"><img src="${image}" alt="${esc(w.title)}"><p class="detail-index">${String(i + 1).padStart(3, "0")} / ${byDate.length}</p></div><div class="detail-copy"><p class="eyebrow">WORK / PROMPT DECODE</p><h1>${esc(w.title)}</h1><div class="meta"><div><b>日期</b>${esc(w.date || "")}</div><div><b>模型 / 工具</b>${esc(w.model || "未注明")}</div><div><b>分类</b>${esc(labels[w.category] || w.category)}</div></div><div class="m-tags">${tags}</div><section class="prompt-block"><div class="prompt-head"><span>完整提示词 Prompt</span><button class="copy-btn" type="button" onclick="navigator.clipboard.writeText(document.querySelector('pre').textContent).then(()=>this.textContent='已复制 ✓')">复制提示词</button></div><pre>${esc(prompt)}</pre></section>${w.notes ? `<section class="section"><h4>备注</h4><div class="body">${esc(w.notes)}</div></section>` : ""}${w.tweet ? `<section class="section"><h4>推文文案</h4><div class="body">${esc(w.tweet)}</div></section>` : ""}<div class="detail-nav"><a href="../${encodeURIComponent(prev.id)}/">← 上一张</a><a href="../${encodeURIComponent(next.id)}/">下一张 →</a></div></div></article>${related.length ? `<section class="related"><p class="eyebrow">MORE LIKE THIS</p><h2>同标签作品</h2><div class="static-grid">${related.map((x) => card(x, 2)).join("")}</div></section>` : ""}`; write(`work/${w.id}/index.html`, shell({ title: titleOf(w), description: desc, level: 2, route: `work/${w.id}/`, og: w.og || "images/og/coolcat-og.webp", content })); }

write("about/index.html", shell({ title: "关于 Coolcat · AI 绘画提示词", description: "Coolcat by @minaoneday，记录 AI 作品、提示词和生成过程。", level: 1, route: "about/", content: `<section class="static-page about-page"><p class="eyebrow">04 / ABOUT</p><h1>关于 Coolcat</h1><p class="static-lede">这是一个带完整提示词的 AI 图像作品集。每一张图都保留生成信息，方便浏览、学习和复用。</p><div class="about-columns"><div><h2>使用说明</h2><p>按分类或标签浏览作品，打开详情页查看完整提示词。提示词可以直接复制，作品可通过独立链接分享。</p></div><div><h2>关于作者</h2><p>Coolcat by <a href="https://x.com/minaoneday" target="_blank" rel="noopener">@minaoneday</a>。作品来自多种图像生成工具，页面会持续更新。</p></div><div><h2>版权说明</h2><p>作品和提示词仅供学习交流。转载或二次使用前，请保留来源并确认原作者授权。</p></div></div></section>` }));

const urls = ["", "gallery/", "gallery/general/", "gallery/portrait/", "gallery/ui/", "about/", ...works.map((w) => `work/${w.id}/`), ...[...tagCounts].filter(([, n]) => n >= 3).map(([tag]) => `tag/${tag.replace(/[\\/:*?"<>|]/g, "-").trim()}/`)];
write("sitemap.xml", `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map((u) => `<url><loc>${base}${u}</loc></url>`).join("")}</urlset>`);
const homeFile = path.join(root, "index.html");
let home = fs.readFileSync(homeFile, "utf8");
const homeCards = works.map((w) => card(w, 0)).join("");
const featured = works.slice(0, 5).map((w) => {
  const label = w.category === "portrait" ? "PORTRAIT" : w.category === "web-ui" ? "UI" : "GENERAL";
  return `<a class="featured-card" href="work/${encodeURIComponent(w.id)}/" aria-label="打开精选作品：${esc(w.title)}"><img src="${w.thumb || w.image}" alt="${esc(w.title)}"><span class="featured-label">${label}</span></a>`;
}).join("");
home = home.replace(/<div id="featured-collage" class="featured-collage" aria-label="精选作品">[\s\S]*?<\/div>/, `<div id="featured-collage" class="featured-collage" aria-label="精选作品">${featured}</div>`);
home = home.replace(/<div id="grid" class="grid">[\s\S]*?<\/div>/, `<div id="grid" class="grid">${homeCards}</div>`);
fs.writeFileSync(homeFile, home);
console.log(`Generated ${works.length} work pages, ${tagCounts.size} tags (${[...tagCounts.values()].filter((n) => n >= 3).length} tag pages), gallery routes and sitemap.`);
